[package]
name = "desmos_lang"
version = "0.1.0"
authors = ["runner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
clap = "2.33.3"

[[bin]]
name = "desmosc"
path = "main.rs"
