[package]
name = "desmos_lang"
version = "0.1.0"
authors = ["Scoder12"]
edition = "2018"

[dependencies]
phf = { version = "0.8.0", features=["macros"] }
ast = { path = "../ast" }
graph = { path = "../graph" }
types = { path = "../types" }
latex = { path = "../latex" }
