[package]
name = "types"
version = "0.1.0"
authors = ["Scoder12"]
edition = "2018"

[dependencies]
ariadne = { version = "0.1.5", optional = true }
chumsky = { version = "0.8.0", optional = true }

[features]
default = []
chumsky = ["dep:chumsky"]
ariadne = ["dep:ariadne"]
