[package]
name = "lsp"
version = "0.1.0"
authors = ["Scoder12"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
desmos_lang = { path = "../desmos_lang" }
lsp-server = "0.6.0"
lsp-types = "0.93.0"
parser = { path = "../parser" }
serde = "1.0.137"
serde_json = "1.0.81"
