[package]
name = "parser"
version = "0.1.0"
authors = ["Scoder12"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
pest_consume = "1.0.6"
desmos_lang = { path = "../desmos_lang" }
