[package]
name = "compiler"
version = "0.1.0"
authors = ["Scoder12"]
edition = "2018"

[dependencies]
pest = "2.1.3"
phf = { version = "0.8.0", features=["macros"] }
desmos_lang = { path = "../desmos_lang" }
